spring:
  application:
    name: Tracker-pro

  datasource:
    url: jdbc:mysql://localhost:3306/trackerpro_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: accessdb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 86400000  # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Email Configuration (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: sathiyan.pm.inzoho@gmail.com          # Replace with your Gmail
    password: gdgkpozyyhxbvbdn    # Replace with App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Custom email settings
app:
  mail:
    from: sathiyan.pm.inzoho@gmail.com              # Sender email
    from-name: TrackerPro HR Team           # Sender display name